# Molecule managed

---
all:
  hosts:
    instance-1-default: &id001
      ansible_host: 127.0.0.1
      ansible_port: '2222'
      ansible_private_key_file: /home/greg/git/personal/plex/ansible-role-transmission/molecule/default/.molecule/.vagrant/machines/instance-1-default/virtualbox/private_key
      ansible_ssh_common_args: -o UserKnownHostsFile=/dev/null -o ControlMaster=auto
        -o ControlPersist=60s -o IdentitiesOnly=yes -o StrictHostKeyChecking=no -o
        ControlPath=~/.ansible/cp/%C
      ansible_user: ubuntu
      connection: ssh
ungrouped:
  hosts:
    instance-1-default: *id001
  vars: {}
