---
  # include distro-specific tasks
  - include: debian.yml
    when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'

  - include: rhel.yml
    when: ansible_distribution == 'CentOS' or ansible_distribution == 'RedHat'
